DROP TABLE IF EXISTS prijave;
DROP TABLE IF EXISTS oglas;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  ime VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('osoba', 'firma') NOT NULL,
  phone VARCHAR(30),
  cv_url VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE oglas (
  OglasID INT PRIMARY KEY AUTO_INCREMENT,
  Pozicija VARCHAR(50),
  Firma VARCHAR(50),
  Lokacija VARCHAR(50),
  Tip VARCHAR(50),
  Iskustvo VARCHAR(50),
  Plata DECIMAL(10,2),
  Datum DATE,
  OpisPosla TEXT,
  user_id INT NOT NULL,
  CONSTRAINT fk_oglas_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE prijave (
  id INT PRIMARY KEY AUTO_INCREMENT,
  oglas_id INT NOT NULL,
  user_id INT NOT NULL,
  datum_prijave TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (oglas_id) REFERENCES oglas(OglasID) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);